try to fix eslint v9.9.0 upgrade issue
GSA/oasis-plus pull request #625
Opened 2024-08-15 18:24 UTC by weiwang-gsa

try to fix dependbot eslint upgrade issue

- seems v9.9.0 needs to use eslint.config.mjs, followed the migration instruction (https://eslint.org/docs/latest/use/configure/migration-guide).

2024-08-16 19:27 UTC, jfredrickson requested changes

2024-08-19 15:02 UTC, weiwang-gsa commented
@jfredrickson I was trying to make the changes accordingly, however, after change it ends up with 2498 errors, those errors are pointing to files under public/js folder, and config files under root level, although I set the ignore rules, it is not taking effects. We probably need to discuss it.
![image](https://github.com/user-attachments/assets/c10f2eb4-fd6a-4198-b4e1-8531010fe38d)
![image](https://github.com/user-attachments/assets/fa6afdee-5f4f-419a-b75f-c8d2a4e2d82d)

2024-08-19 16:52 UTC, jfredrickson commented
@weiwang-gsa I misunderstood the `files` directive in the configuration, never mind!

2024-08-19 16:52 UTC, jfredrickson approved these changes

2024-08-19 18:16 UTC, merged