Add files via upload - Item for Sellers page Systems, Tools and Registration sellers guide
GSA/oasis-plus pull request #693
Opened 2024-09-20 21:37 UTC by smteague

2024-09-20 21:58 UTC, smteague commented
@weiwang-gsa Hello Wei, in this patch I uploaded a pdf and then linked to in from the Resources page. When I looked at the sandbox page for this branch and opened the file from the Resources page, it actually opened in a github frame, which I don't think it's supposed to do. Maybe it's because the file itself hasn't been pushed live, but I think I might have done something wrong. Thank you for taking a look at it when you can.

2024-09-23 12:41 UTC, weiwang-gsa requested changes
@smte

2024-09-23 12:41 UTC, weiwang-gsa commented on src/content/resources/index.mdx
> +| [OASIS+ Systems, Tools, and Registration Sellers Guide](https://github.com/GSA/oasis-plus/blob/smteague-patch-2/public/files/OASIS%2B_Systems%2C%20Tools%2C%20and%20Registration_Sellers%20Guide_%20S
@smteague when we uploaded file to public folder, it is not external link, we can't use the github branch link as the link, you should remove http part all the way util you reached the "/files/", like this
.  when you `[OASIS+ Systems, Tools, and Registration Sellers Guide](/files/OASIS%2B_Systems%2C%20Tools%2C%20and%20Registration_Sellers%20Guide_%20Sep%202024%20(508).pdf)`, there is reference in the [how to doc](https://docs.google.com/document/d/1UgbWZZrSoaZpejDhbOkbiZLYfALajJDnKIjbZDPizRM/edit), you can give a try, and see if it resolve your issue, please ping me when you need help, I can help you correct it

2024-09-30 13:21 UTC, weiwang-gsa reviewed
The link itself looks perfect!! Just same suggest as the other PR, for the internal file link, maybe better to put file type indication in the link text, so person with vision impairment know the link is not link to a web page. USWDS suggest sth like below:

<img width="811" alt="image" src="https://github.com/user-attachments/assets/ef99f29c-64a9-4427-9827-b0b61b9814ea">

2024-09-30 20:15 UTC, weiwang-gsa approved these changes
Looks great to me!

2024-09-30 20:29 UTC, merged